/****************************************************************************
rc.h
*****************************************************************************/

#define ID_ABOUT    80

#define IDC_SECRET  101
#define IDC_TEXT    102
#define IDC_SAVEPK  103
#define IDC_MAKEPK  104
#define IDC_SELPK   105
#define IDC_DELPK   106
#define IDC_SIG     107
#define IDC_ENC     108
#define IDC_DEC     109
#define IDC_VER     110
#define IDC_BROWSE  111
#define IDC_WIN     112
#define IDC_CLIPB   113
#define IDC_FILE    114
#define IDC_FILENAME 115
#define IDC_BIN	    116
#define IDC_PKNAME  117
#define IDC_PKDATA  118
#define IDT_SECRET  119
#define IDT_PK      120
#define IDC_CONV    121
#define IDC_SHOWPW  122
#define IDC_TOSELF  123
#define IDT_KEYNUM  124
#define IDC_KEYNUM  125

#define IDC_PKLIST  130
#define IDC_LIST    131
#define IDC_SETDEF  132
